### ISSUE TITLE
no font and css generation

### ISSUE THREAD

**Issue by SlimMarten** [Workshape/icon-font-generator#15]
when running icon-font-generator, it logs "Generating font kit from 3 SVG icons" in the console but is not generating css or fonts at all.

this is my task config:

`icon-font-generator src/icon-font/*svg -o public/assets/fonts/mesh-icons --html false --name mesh-icons --fontspath ../fonts/mesh-icons/ --csspath src/scss/settings/icon-font.scss --j false`

**Comment by tancredi** [comment]
Hi @SlimMarten, I've attempted to replicate your directory structure and run a test and it works fine for me (see screenshot) what environment are you running this from?

![Screenshot](http://i.cubeupload.com/6OdZrx.png)

**Comment by SlimMarten** [comment]
Running on Node v8.2.1.

I noticed that the problem only occurs if the svg contains svg shapes like <rect>. If I convert my shapes to <paths> everything works fine.
