### ISSUE TITLE
Unicode range

### ISSUE THREAD

**Issue by benp** [Workshape/icon-font-generator#18]
Hi, I was wondering if there's a way to specify at what unicode number the glyphs start?
Thanks :)

**Comment by jooleeanh** [comment]
Would really appreciate having a flag to specify a starting unicode number.
It would also be nice to see this unicode number in the html file. Thanks!

**Comment by colonelpopcorn** [comment]
I'd also like to see some more options around unicode text. In the underlying webfonts-generator there is an option to pass an object with unicode-SVG mappings. Should I get a pull request together?

**Comment by tancredi** [comment]
The PR was merged - does this do the job for everyone? Also, if anyone could help me test that everything works fine on Windows that would be great. Thanks @colonelpopcorn for the contribution 🌯 🍔 🍳

**Comment by colonelpopcorn** [comment]
I used Windows primarily for testing.

**Comment by tancredi** [comment]
there was another PR that solved the Windows issue more concisely (and was already merged) so I went with that one - though I can only test for Mac - let me know whether it all works smoothly Colonel 🍿 ;)

**Comment by tancredi** [comment]
Any news on this @colonelpopcorn ?

**Comment by colonelpopcorn** [comment]
Yeah man, it works good! Thanks!

😀:shipit:😀
