### ISSUE TITLE
Change font type source call

### ISSUE THREAD

**Issue by fccoelho7** [Workshape/icon-font-generator#21]
Hi folks,

I implemented this CLI in my Rails project, BUT, in Rails, we need import fonts passing:
`src: font-url('path')`

Any suggestion to manipulate the string that comes from `webfonts-generator` pack?

I thought in creating a Handlebar's helper or a subcommand that fix the SCSS file generated by CLI.

**Comment by tancredi** [comment]
Could you not just pass it a custom css template and output with a `.scss` ext in the filename using the `--csspath` and `--csstp` options?
