### ISSUE TITLE
Feature request: Option for vertical-align

### ISSUE THREAD

**Issue by DanielTheCoder** [Workshape/icon-font-generator#27]
Is it possible to add an option for "vertical-align" like we have for fontName?

**Comment by tancredi** [comment]
Good suggestion @DanielTheCoder - though as this relies on https://github.com/sunflowerdeath/webfonts-generator we can only use options that it will accept - I can't see anything of that sort. Ideas?

**Comment by DanielTheCoder** [comment]
I was thinking of extending the existing template [scss.hbs](https://github.com/sunflowerdeath/webfonts-generator/blob/master/templates/scss.hbs) with a good default for vertical-align and make it overrideable like fontName

**Comment by tancredi** [comment]
Oh I didn't realise you were just talking about CSS - I would probably add that manually in your CSS by matching the selector or just targeting all `i` tags - I often have to write some custom styling to my icons even after generating the CSS, but I wouldn't feel like making that part of the 'minimum viable CSS' required to get the icons to functionally work.
