### ISSUE TITLE
Class instead of element

### ISSUE THREAD

**Issue by LucasKA** [Workshape/icon-font-generator#4]
Great package guys. Super usable and helpful. I'm trying to move away from Icomoon to a more automated thing, and trying to get a similar output to it's CSS.

A big one, is targeting a class instead of an element. we use `<span class="icon-name"></span>`

and Icomoon outputs

```
[class^="icon-"], [class*=" icon-"] {
  /* use !important to prevent issues with browser extensions that change fonts */
  font-family: 'fender-icons' !important;
  speak: none;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;

  /* Better Font Rendering =========== */
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

I can't seem to figure out how to replicate that first line with icon-font-generator. Any suggestions?

**Comment by tancredi** [comment]
Hi Lucas, a couple notes:

When running icon-font-generator, you can use the `--prefix` parameter (or `-p`) to specify the CSS classname prefix to use with your icon - e.g. `-p icon` will generate classnames such as `.icon-key`.

If you want to have extra control over the CSS output, you can also use a custom Handlebars template to generate the CSS - just point the `--csstp` parameter to your template - find the default one used by icon-font-generator [here](https://github.com/Workshape/icon-font-generator/blob/master/template/css.hbs)

**Note:** I've just realised there's a small bug that makes the `--prefix` parameter default to `icons-` as opposed to `icon-` (which would be the correct default declared in the documentation and help prompt) - this will be fixed soon.

Hope this was helpful, don't hesitate to ask if you have any more doubts.

**Comment by spacecowboyian** [comment]
Is it possible to make/use handlebars helpers?

**Comment by tancredi** [comment]
@spacecowboyian not at the minute, sorry
