### ISSUE TITLE
for circle svg lose shape

### ISSUE THREAD

**Issue by m1911star** [Workshape/icon-font-generator#43]
as below
![image](https://user-images.githubusercontent.com/4948120/46148444-aabc0100-c29a-11e8-8216-807fa21ce0e2.png)
![image](https://user-images.githubusercontent.com/4948120/46148564-f4a4e700-c29a-11e8-93cd-e06863f98edf.png)

**Comment by brunogeronimo** [comment]
Hello,
What is the current status of this issue? I'm asking because I'm facing the same issue in my company.

**Comment by brunogeronimo** [comment]
Hey!
I've fixed this issue including `--height=1000` as parameter when generating the font files (see #17).

**Comment by m1911star** [comment]
> Hey!
> I've fixed this issue including `--height=1000` as a parameter when generating the font files (see #17).

oh my, great!!!! thanks !!! fixed !
