### ISSUE TITLE
Can't disable rounding

### ISSUE THREAD

**Issue by pashtet86** [Workshape/icon-font-generator#45]
Hi, have some issues I guess with rounding. For example instead of this
<img width="132" alt="screenshot 2018-10-09 22 27 13" src="https://user-images.githubusercontent.com/11823971/46693468-83f2b880-cc12-11e8-8982-e3a92394ce10.png">
I'm getting 
<img width="94" alt="screenshot 2018-10-09 22 29 17" src="https://user-images.githubusercontent.com/11823971/46693542-c74d2700-cc12-11e8-8a06-1bc74266d318.png">

  trying to disable rounding by setting --round 0, --round false but id doesn't work.

**Comment by tancredi** [comment]
Hi @pashtet86 - did you find the solution? (same as https://github.com/Workshape/icon-font-generator/issues/43)

**Comment by tancredi** [comment]
Probably a good idea, yes. At some point I'd like to make all the answered issues into a bit of a Wiki / User guide. Just a bit short in time lately.

Thanks
