### ISSUE TITLE
generate js file 

### ISSUE THREAD

**Issue by sibelius** [Workshape/icon-font-generator#6]
something like this: https://github.com/entria/react-native-fontawesome/blob/master/FontAwesomeIcons.js

it would be very helpful

**Comment by sibelius** [comment]
related to https://github.com/sunflowerdeath/webfonts-generator/issues/25

**Comment by tancredi** [comment]
Hi - that's what the `--json` option already does, just require the JSON file from your JS - it's actually cleaner this way as it can be supported by more languages.
