### ISSUE TITLE
Generated fonts with evenodd fill rule not rendering properly in Windows

### ISSUE THREAD

**Issue by symphony-adnane** [Workshape/icon-font-generator#82]
Hello all, 
I'm facing a kind of bizarre issue with some svg icons, after generating fonts, they'd appear as expected under Mac, but totally wrong in windows. 
Example with this circle alert icon: 

[alert-round.svg.zip](https://github.com/Workshape/icon-font-generator/files/5340670/alert-round.svg.zip)
Under Mac: 
![image](https://user-images.githubusercontent.com/63653674/95332183-5a290680-08ab-11eb-8672-c64fd5a0ddf5.png)
Under Windows:
![image](https://user-images.githubusercontent.com/63653674/95332742-213d6180-08ac-11eb-88a1-dfec03b5cd21.png)

I used SVGO to cleanup all my icons, but not solving the issue. 
Note that this doesn't happen with all the icons, some of them would render just perfect
Thanks in advance

**Comment by tancredi** [comment]
Try this

[alert-round.svg-2.zip](https://github.com/Workshape/icon-font-generator/files/5340866/alert-round.svg-2.zip)

**Comment by symphony-adnane** [comment]
Thank you @tancredi  this worked perfect, 
May you explain what happened :) , why is this happening only on Windows? 
I have several of them giving the same issue

**Comment by tancredi** [comment]
Not sure about windows, just opened the SVG in Illustrator and fixed it up as it displayed like so:

<img width="265" alt="Screenshot 2020-10-07 at 15 58 59" src="https://user-images.githubusercontent.com/1300753/95341962-2b189200-08b7-11eb-8694-e3e2327828bd.png">

May be the use of `fill-rule="evenodd"` but I'm really not that versed in SVG specifications

**Comment by symphony-adnane** [comment]
oh ok thanks anyway for pointing that out

**Comment by symphony-adnane** [comment]
Fixed by reworking the SVGs to avoid evenodd filling rule. 
This is a common problem preventing Fonts and Android svg rendering from working properly 
There is this awesome plugin that helps converting from even odd to non-zero

https://twitter.com/evanwallace/status/1189594907989565440
